name: Provenance_Java_CI_with_Maven
on: [push]
permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@v1.10.0



#jobs:
#  build:
#    permissions:
#      id-token: write
#      contents: write
#    name: Build Code
#    runs-on: ubuntu-latest
#    steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - name: Cache the Maven packages to speed up build
#       uses: actions/cache@v1
#       with:
#         path: ~/.m2
#         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#         restore-keys: ${{ runner.os }}-m2   
#     - name: Build with Maven
#       run: mvn -B clean verify --file pom.xml
#     - run: ls -lart ${GITHUB_WORKSPACE}/sm-shop/target/
#     - uses: github-early-access/generate-build-provenance@main
       with:
         subject-path: '${{ github.workspace }}/sm-shop/target/ROOT.war'
